name: php-cs-fixer

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: cs2pr, php-cs-fixer

      - name: Run php-cs-fixer
        run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
